<definition> ::= "(" "define" <symbol> <expression> ")"
               | "(" "define" "(" <symbol> <symbol>* ")" <expression>* ")"

<expression> ::= <symbol>
               | <number>
               | <string>
               | "(" <expression>* ")"
