#lang racket
(require "parser.rkt")
(require "tea-to-js.rkt")
(require "sanitize-ids.rkt")
(require "js-expansions.rkt")
(require "js-to-text.rkt")
(require "integration.rkt")
(require "eval.rkt")
(require "string-utilities.rkt")
(display (port->string (first (process "rhino environment.js"))))
